[[shards]]
name = "Hanoi"
idx = 0
address = "127.0.0.1:8080"
replicas = ["127.0.0.1:8090"]

[[shards]]
name = "Sai Gon"
idx = 1
address = "127.0.0.1:8081"
replicas = ["127.0.0.1:8091"]

[[shards]]
name = "Da Nang"
idx = 2
address = "127.0.0.1:8082"
replicas = ["127.0.0.1:8092"]

[[shards]]
name = "Thanh Hoa"
idx = 3
address = "127.0.0.1:8083"
replicas = ["127.0.0.1:8093"]

